# Generated by Django 4.1.5 on 2023-01-13 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='account_type',
            field=models.CharField(choices=[('SAVINGS ACCOUNT', 'SAVINGS ACCOUNT'), ('CURRENT ACCOUNT', 'CURRENT ACCOUNT')], max_length=20),
        ),
    ]
